coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true

comment:
  layout: "header, diff, files"
  behavior: default
  require_changes: false

ignore:
  - "src/pycse/tests/**"
  - "src/pycse/sklearn/examples/**"
  - "setup.py"
  - "docker/**"
