repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    - id: black
      entry: black --line-length 100 src/pycse

  - repo:  https://github.com/PyCQA/flake8
    rev: 7.1.0
    hooks:
    - id: flake8
      # install the plugin so flake8 reads pyproject.toml
      additional_dependencies:
        - flake8-pyproject
      entry: flake8 --max-line-length 100 src/pycse

  - repo: local
    hooks:
    - id: pytest
      name: pytest
      entry: pytest
      language: system
      types: [python]
      pass_filenames: false
      always_run: true

  # - repo: local
  #   hooks:
  #   - id: pylint
  #     name: pylint
  #     entry: pylint pycse || true
  #     language: system
  #     types: [python]
  #     args:
  #       [
  #       "--rcfile=setup.cfg",
  #       "-rn", # Only display messages
  #       "-sn", # Don't display the score
  #       ]
