#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options:
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : pycse - Python Computations in Science and Engineering  # The title of the book. Will be placed in the left navbar.
author                      : John Kitchin  # The author of the book
copyright                   : "2023"  # Copyright year to be placed in the footer
logo                        : pycse.png  # A path to the book logo

exclude_patterns: [book/archive/*]

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  allow_errors: true

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/jkitchin/pycse  # Online location of your book
  path_to_book: pycse-jb/pycse___python_computations_in_science_and_engineering/  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  analytics:
    google_analytics_id: G-4H7VFJKEZY
  comments:
    utterances:
      repo: jkitchin/dsmles
    hypothesis: true
  extra_footer: |
    <!-- RAG Chat Widget - Self-contained version for Jupyter Book -->
    <style>
    /* RAG Widget Styles */
    :root {
        --widget-primary-color: #1f77b4;
        --widget-primary-hover: #1565a8;
        --widget-bg-color: #ffffff;
        --widget-text-color: #262730;
        --widget-border-color: #e0e0e0;
        --widget-shadow: 0 8px 24px rgba(0, 0, 0, 0.15);
        --widget-shadow-lg: 0 12px 32px rgba(0, 0, 0, 0.2);
        --widget-border-radius: 16px;
        --widget-button-size: 60px;
        --widget-z-index: 9999;
    }

    .rag-widget {
        position: fixed;
        z-index: var(--widget-z-index);
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Helvetica', 'Arial', sans-serif;
        bottom: 20px;
        right: 20px;
    }

    .widget-button {
        width: var(--widget-button-size);
        height: var(--widget-button-size);
        border-radius: 50%;
        background-color: var(--widget-primary-color);
        border: none;
        box-shadow: var(--widget-shadow);
        cursor: pointer;
        display: flex;
        align-items: center;
        justify-content: center;
        transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
        position: relative;
        overflow: hidden;
    }

    .widget-button:hover {
        background-color: var(--widget-primary-hover);
        box-shadow: var(--widget-shadow-lg);
        transform: scale(1.05);
    }

    .widget-button:active {
        transform: scale(0.95);
    }

    .widget-icon,
    .widget-close-icon {
        width: 28px;
        height: 28px;
        color: white;
        transition: all 0.3s ease;
        position: absolute;
    }

    .widget-close-icon {
        opacity: 0;
        transform: rotate(90deg) scale(0);
    }

    .widget-button.active .widget-icon {
        opacity: 0;
        transform: rotate(-90deg) scale(0);
    }

    .widget-button.active .widget-close-icon {
        opacity: 1;
        transform: rotate(0deg) scale(1);
    }

    .widget-container {
        position: fixed;
        bottom: 90px;
        right: 20px;
        width: min(50vw, calc(100vw - 40px));
        height: min(600px, calc(100vh - 120px));
        max-width: calc(100vw - 40px);
        max-height: calc(100vh - 120px);
        background-color: var(--widget-bg-color);
        border-radius: var(--widget-border-radius);
        box-shadow: var(--widget-shadow-lg);
        display: flex;
        flex-direction: column;
        overflow: hidden;
        opacity: 0;
        transform: scale(0.9) translateY(10px);
        transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
        pointer-events: none;
    }

    .widget-container.visible {
        opacity: 1;
        transform: scale(1) translateY(0);
        pointer-events: all;
    }

    .widget-container.hidden {
        display: none;
    }

    .widget-header {
        background-color: var(--widget-primary-color);
        color: white;
        padding: 16px 20px;
        display: flex;
        align-items: center;
        justify-content: space-between;
        flex-shrink: 0;
    }

    .widget-header-content {
        flex: 1;
    }

    .widget-title {
        margin: 0;
        font-size: 18px;
        font-weight: 600;
        line-height: 1.2;
    }

    .widget-subtitle {
        margin: 4px 0 0 0;
        font-size: 13px;
        opacity: 0.9;
        line-height: 1.2;
    }

    .widget-minimize-btn {
        background: none;
        border: none;
        color: white;
        cursor: pointer;
        padding: 8px;
        display: flex;
        align-items: center;
        justify-content: center;
        border-radius: 8px;
        transition: background-color 0.2s ease;
    }

    .widget-minimize-btn:hover {
        background-color: rgba(255, 255, 255, 0.1);
    }

    .widget-minimize-btn svg {
        width: 20px;
        height: 20px;
    }

    .widget-iframe-container {
        flex: 1;
        position: relative;
        overflow: hidden;
        background-color: #f5f5f5;
    }

    #widget-iframe {
        width: 100%;
        height: 100%;
        border: none;
    }

    .widget-footer {
        padding: 12px 20px;
        background-color: var(--widget-bg-color);
        border-top: 1px solid var(--widget-border-color);
        text-align: center;
        flex-shrink: 0;
    }

    .widget-powered-by {
        font-size: 12px;
        color: #666;
    }

    .widget-powered-by a {
        color: var(--widget-primary-color);
        text-decoration: none;
        font-weight: 500;
    }

    .widget-powered-by a:hover {
        text-decoration: underline;
    }

    @media (max-width: 768px) {
        .widget-container {
            width: 100%;
            height: 100%;
            max-width: 100%;
            max-height: 100%;
            bottom: 0;
            right: 0;
            left: 0;
            top: 0;
            border-radius: 0;
        }

        .widget-button {
            width: 56px;
            height: 56px;
        }

        .widget-icon,
        .widget-close-icon {
            width: 24px;
            height: 24px;
        }
    }

    @media (max-width: 480px) {
        .rag-widget {
            bottom: 16px;
            right: 16px;
        }
    }

    .widget-iframe-container::before {
        content: '';
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        width: 40px;
        height: 40px;
        border: 3px solid #f3f3f3;
        border-top: 3px solid var(--widget-primary-color);
        border-radius: 50%;
        animation: widget-spin 1s linear infinite;
        opacity: 0;
        transition: opacity 0.3s ease;
    }

    .widget-iframe-container.loading::before {
        opacity: 1;
    }

    @keyframes widget-spin {
        0% { transform: translate(-50%, -50%) rotate(0deg); }
        100% { transform: translate(-50%, -50%) rotate(360deg); }
    }

    @media (prefers-color-scheme: dark) {
        :root {
            --widget-bg-color: #1e1e1e;
            --widget-text-color: #ffffff;
            --widget-border-color: #333333;
        }

        .widget-iframe-container {
            background-color: #252525;
        }
    }

    .widget-button:focus,
    .widget-minimize-btn:focus {
        outline: 2px solid var(--widget-primary-color);
        outline-offset: 2px;
    }

    @media print {
        .rag-widget {
            display: none !important;
        }
    }
    </style>

    <div id="rag-widget" class="rag-widget">
        <!-- Floating Button -->
        <button id="widget-button" class="widget-button" aria-label="Open chat">
            <svg class="widget-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
                <path d="M20 2H4c-1.1 0-2 .9-2 2v18l4-4h14c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm0 14H6l-2 2V4h16v12z"/>
                <path d="M7 9h2v2H7zm4 0h2v2h-2zm4 0h2v2h-2z"/>
            </svg>
            <svg class="widget-close-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
                <path d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"/>
            </svg>
        </button>

        <!-- Chat Container -->
        <div id="widget-container" class="widget-container hidden">
            <!-- Header -->
            <div class="widget-header">
                <div class="widget-header-content">
                    <h3 class="widget-title">Secret A(i)gent</h3>
                    <p class="widget-subtitle">Ask me anything</p>
                </div>
                <button id="widget-minimize" class="widget-minimize-btn" aria-label="Minimize chat">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
                        <path d="M19 13H5v-2h14v2z"/>
                    </svg>
                </button>
            </div>

            <!-- Chat iframe -->
            <div class="widget-iframe-container">
                <iframe
                    id="widget-iframe"
                    src=""
                    frameborder="0"
                    allow="clipboard-write"
                    title="RAG Chat Assistant">
                </iframe>
            </div>

            <!-- Footer -->
            <div class="widget-footer">
                <span class="widget-powered-by">
                    Powered by <a href="https://github.com/jkitchin/streamlit-rag-widget" target="_blank">a Secret A(i)gent</a>
                </span>
            </div>
        </div>
    </div>

    <script>
    /**
     * RAG Widget Configuration and Script
     */
    (function() {
        'use strict';

        // Configuration
        const config = {
            streamlitUrl: 'https://kitchin-services.cheme.cmu.edu',
            position: 'bottom-right',
            width: '50vw',
            height: '600px',
            primaryColor: '#1f77b4',
            title: 'Secret A(i)gent',
            subtitle: 'Ask me anything',
            showPoweredBy: true,
            autoOpen: false,
            openDelay: 0,
            zIndex: 9999,
        };

        // Widget state
        let isOpen = false;

        // Get DOM elements
        const widget = document.getElementById('rag-widget');
        const button = document.getElementById('widget-button');
        const container = document.getElementById('widget-container');
        const iframe = document.getElementById('widget-iframe');
        const minimizeBtn = document.getElementById('widget-minimize');
        const iframeContainer = document.querySelector('.widget-iframe-container');

        if (!widget || !button || !container || !iframe) {
            console.error('RAG Widget: Required elements not found');
            return;
        }

        /**
         * Initialize widget
         */
        function init() {
            // Set iframe URL
            iframe.src = config.streamlitUrl;

            // Set custom colors
            if (config.primaryColor) {
                document.documentElement.style.setProperty('--widget-primary-color', config.primaryColor);
            }

            // Set title and subtitle
            const title = document.querySelector('.widget-title');
            const subtitle = document.querySelector('.widget-subtitle');
            if (title && config.title) {
                title.textContent = config.title;
            }
            if (subtitle && config.subtitle) {
                subtitle.textContent = config.subtitle;
            }

            // Hide powered by if configured
            if (!config.showPoweredBy) {
                const footer = document.querySelector('.widget-footer');
                if (footer) {
                    footer.style.display = 'none';
                }
            }

            // Add event listeners
            button.addEventListener('click', toggleWidget);
            minimizeBtn.addEventListener('click', closeWidget);

            // Handle keyboard shortcuts
            document.addEventListener('keydown', function(event) {
                if (event.key === 'Escape' && isOpen) {
                    closeWidget();
                }
            });

            // Auto-open if configured
            if (config.autoOpen) {
                setTimeout(openWidget, config.openDelay);
            }

            console.log('RAG Widget initialized');
        }

        /**
         * Toggle widget open/closed
         */
        function toggleWidget() {
            if (isOpen) {
                closeWidget();
            } else {
                openWidget();
            }
        }

        /**
         * Open widget
         */
        function openWidget() {
            isOpen = true;
            button.classList.add('active');
            container.classList.remove('hidden');

            setTimeout(function() {
                container.classList.add('visible');
            }, 10);

            setTimeout(function() {
                iframe.focus();
            }, 300);
        }

        /**
         * Close widget
         */
        function closeWidget() {
            isOpen = false;
            button.classList.remove('active');
            container.classList.remove('visible');

            setTimeout(function() {
                container.classList.add('hidden');
            }, 300);
        }

        /**
         * Public API
         */
        window.RAGWidget = {
            open: openWidget,
            close: closeWidget,
            toggle: toggleWidget,
            isOpen: function() { return isOpen; }
        };

        // Initialize when DOM is ready
        if (document.readyState === 'loading') {
            document.addEventListener('DOMContentLoaded', init);
        } else {
            init();
        }

    })();
    </script>


launch_buttons:
  colab_url: "https://colab.research.google.com"
  notebook_interface: "jupyterlab"
  jupyterhub_url: "https://lab.amdatascience.com/"

sphinx:
  extra_extensions:
  - 'numpydoc'
  - 'sphinx.ext.autodoc'
  config:
    nb_execution_show_tb: True
