#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : pycse - Python Computations in Science and Engineering  # The title of the book. Will be placed in the left navbar.
author                      : John Kitchin  # The author of the book
copyright                   : "2023"  # Copyright year to be placed in the footer
logo                        : pycse.png  # A path to the book logo

exclude_patterns: [book/archive/*]

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  allow_errors: true

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/jkitchin/pycse  # Online location of your book
  path_to_book: pycse-jb/pycse___python_computations_in_science_and_engineering/  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  google_analytics_id: G-4H7VFJKEZY
  comments:
    utterances:
      repo: jkitchin/dsmles
    hypothesis: true
    
launch_buttons:
  colab_url: "https://colab.research.google.com"
  notebook_interface: "jupyterlab"
  jupyterhub_url: "https://lab.amdatascience.com/"
  
sphinx:
  extra_extensions:
  - 'numpydoc'
  - 'sphinx.ext.autodoc'
  config:
    nb_execution_show_tb: True  
