#!/bin/bash                                                                              
                                                                                         
~/.local/share/pyppeteer/local-chromium/588429/chrome-linux/chrome-exe --no-sandbox "$@" 

#end   