build:
	jupyter book build pycse___python_computations_in_science_and_engineering
	open pycse___python_computations_in_science_and_engineering/_build/html/index.html

clean:
	jupyter book clean pycse___python_computations_in_science_and_engineering

deploy:
	ghp-import -n -p -f pycse___python_computations_in_science_and_engineering/_build/html
