build:
	jupyter book build pycse___python_computations_in_science_and_engineering/
	open pycse___python_computations_in_science_and_engineering/_build/html/index.html


deploy:
	ghp-import -n -p -f pycse___python_computations_in_science_and_engineering/_build/html
